### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by kusumajati51** [DeniferSantiago/mdi-vuetify-intellisense#3]
- Issue Type: `Bug`
- Extension Name: `mdi-vuetify-intellisense`
- Extension Version: `0.3.2`
- OS Version: `Linux x64 5.4.0-56-generic`
- VSCode version: `1.52.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DeniferSantiago** [comment]
when do you get that error message? @kusumajati51
