### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MaxJohnson** [DeniferSantiago/mdi-vuetify-intellisense#4]
- Issue Type: `Performance`
- Extension Name: `mdi-vuetify-intellisense`
- Extension Version: `0.3.2`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.52.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\max\AppData\Local\Temp\Denifer.mdi-vuetify-intellisense-unresponsive.cpuprofile.txt
[Denifer.mdi-vuetify-intellisense-unresponsive.cpuprofile.txt](https://github.com/DeniferSantiago/mdi-vuetify-intellisense/files/5705998/Denifer.mdi-vuetify-intellisense-unresponsive.cpuprofile.txt)
`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DeniferSantiago** [comment]
Thank you so much for reporting it, I checked and will be going through the code to fix it.  The extension can use a lot of cpu the first time intellisense is used after opening VS Code, does it happen to you that way?
